name: catalog-entry

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # every day at midnight

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-and-generate:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5.1.0
        with:
          python-version: "3.12"
      - name: validate feedstock entry and generate catalog
        uses: leap-stc/data-catalog-actions/leap-catalog@main
        with:
          generation-single: "./feedstock/catalog.yaml"
          output-directory: "./"

      - name: display catalog
        run: |
          cat output/single-feedstock-web-catalog.json | jq

      - name: Upload artifacts
        uses: actions/upload-artifact@v4.1.0
        with:
          name: single-feedstock-web-catalog.json
          path: output/single-feedstock-web-catalog.json

  update:
    needs: validate-and-generate
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    environment:
      name: update-environment
      url: https://catalog.leap.columbia.edu/?catalog=https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref }}/output/single-feedstock-web-catalog.json
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pull Remote Changes
        run: |
          git pull origin ${{ github.ref }} --rebase --autostash

      - uses: actions/download-artifact@v4.1.0
        with:
          name: single-feedstock-web-catalog.json
          path: output

      - name: Format JSON
        run: |
          jq . output/single-feedstock-web-catalog.json > formatted.json
          mv formatted.json output/single-feedstock-web-catalog.json

      - name: Create Pull Request
        id: cpr
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || github.event_name == 'push'
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "build: update catalog entry"
          committer: GitHub <noreply@github.com>
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          title: Update catalog entry
          body: |
            - Updates the single-feedstock web catalog for changes on `main`
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          branch: update-single-feedstock-web-catalog
          delete-branch: true
